# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build .NET Framework app on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 'latest'
        
    - name: Restore NuGet packages
      run: nuget restore PoePart1Project.sln
      
    - name: Build Solution
      run: msbuild PoePart1Project.sln /p:Configuration=Release
